### ISSUE TITLE
samples/bumptest.bmx: Texture is not a render target texture

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/mky.mod#1]
Error only happens when doing a release build. The debug build runs fine.

All other samples work as expected (assume so).

**Comment by woollybah** [comment]
Have you the latest bcc? Have you rebuilt the module with it?

**Comment by GWRon** [comment]
fetched bcc brl pub. Rebuilt bcc...and disabled quick build

It rebuilt one module ...some basic one...but nothing more.

Will check further when at home again.

**Comment by woollybah** [comment]
There was an issue when referring to consts in modules, from within an (internally) imported file. Values were being exposed from the module's API as zero value.

This was fixed recently.

**Comment by GWRon** [comment]
will force-recompile modules at home..  bmk cannot know that it has to recompile modules because of changes in bcc (could be overcome but this is "too much")

**Comment by woollybah** [comment]
Indeed, whenever changes to bcc result in changes to the generated code, it's safest just to do a full rebuild of everything.
In fact, whenever you get a new bcc, you may as well rebuild everything - just to be sure.

**Comment by GWRon** [comment]
The complete module rebuild indeed fixed the issue.
